--===================================================
--STUDENT/STUDNET계정 생성후 전체실행(F5)할 것!!
--===================================================
﻿DROP TABLE PRODUCT_STOCK;
DROP TABLE PRODUCT_IO;

CREATE TABLE PRODUCT_STOCK (
  PRODUCT_ID  VARCHAR2(30) PRIMARY KEY,
  PRODUCT_NAME  VARCHAR2(30)  NOT NULL,
  PRICE NUMBER(10)  NOT NULL,
  DESCRIPTION VARCHAR2(4000),
  STOCK NUMBER DEFAULT 0 
);  

CREATE TABLE PRODUCT_IO(
  IO_NO NUMBER PRIMARY KEY,
  PRODUCT_ID VARCHAR2(30),
  IODATE DATE DEFAULT SYSDATE,
  AMOUNT NUMBER,
  STATUS CHAR(1) CHECK (STATUS IN ('I', 'O')),
  CONSTRAINT FK_PRODUCT_IO FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_STOCK(PRODUCT_ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_PRODUCT_IO_NO
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE;

--입출고 내역에 따라 상품테이블(product_stock)의 재고량을 갱신시키는 trigger
CREATE OR REPLACE TRIGGER TRG_PRODUCT
  AFTER 
  INSERT ON PRODUCT_IO -- PRODUCT_IO 테이블에 ON 시키기
  FOR EACH ROW
BEGIN
  IF :NEW.STATUS='I'
  THEN 
    UPDATE PRODUCT_STOCK
    SET STOCK = STOCK + :NEW.AMOUNT-- STOCK 의 값에 새로 추가되는 AMOUNT값을 더하여라
    WHERE PRODUCT_ID = :NEW.PRODUCT_ID;-- 새로 들어오는 PCODE 값과 PRODUCT의 PCODE값이 일치하는것을 찾아라
  ELSIF :NEW.STATUS='O'
  THEN
    UPDATE PRODUCT_STOCK
    SET STOCK = STOCK - :NEW.AMOUNT
    WHERE PRODUCT_ID = :NEW.PRODUCT_ID;
  END IF;
END;
/

--상품정보 insert
INSERT INTO PRODUCT_STOCK VALUES ('nb_ss7', '삼성노트북', 1570000, '시리즈 7', DEFAULT);
INSERT INTO PRODUCT_STOCK VALUES ('nb_macbook_air', '맥북에어', 1200000, 'xcode 4', DEFAULT);
INSERT INTO PRODUCT_STOCK VALUES ('pc_ibm', 'ibmPC', 750000, 'windows 8', DEFAULT);


--입출고정보 insert
INSERT INTO PRODUCT_IO VALUES(SEQ_PRODUCT_IO_NO.NEXTVAL,'nb_ss7' , DEFAULT, 30, 'I');
INSERT INTO PRODUCT_IO VALUES(SEQ_PRODUCT_IO_NO.NEXTVAL,'nb_ss7' , DEFAULT, 5, 'O');

COMMIT;

SELECT * FROM PRODUCT_STOCK;
SELECT * FROM PRODUCT_IO;
SELECT * FROM USER_TRIGGERS;